var cards = [{
            "displayName":"Geezard",
            "image":"card0",
            "strengthUp":1,
            "strengthRight":4,
            "strengthDown":1,
            "strengthLeft":5,
            "element":0
         },{
            "displayName":"Funguar",
            "image":"card1",
            "strengthUp":5,
            "strengthRight":1,
            "strengthDown":1,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"Bite Bug",
            "image":"card2",
            "strengthUp":1,
            "strengthRight":3,
            "strengthDown":3,
            "strengthLeft":5,
            "element":0
         },{
            "displayName":"Red Bat",
            "image":"card3",
            "strengthUp":6,
            "strengthRight":1,
            "strengthDown":1,
            "strengthLeft":2,
            "element":0
         },{
            "displayName":"Blobra",
            "image":"card4",
            "strengthUp":2,
            "strengthRight":3,
            "strengthDown":1,
            "strengthLeft":5,
            "element":0
         },{
            "displayName":"Gayla",
            "image":"card5",
            "strengthUp":2,
            "strengthRight":1,
            "strengthDown":4,
            "strengthLeft":4,
            "element":2
         },{
            "displayName":"Gesper",
            "image":"card6",
            "strengthUp":1,
            "strengthRight":5,
            "strengthDown":4,
            "strengthLeft":1,
            "element":0
         },{
            "displayName":"Fastitocalon-F",
            "image":"card7",
            "strengthUp":3,
            "strengthRight":5,
            "strengthDown":2,
            "strengthLeft":1,
            "element":5
         },{
            "displayName":"Blood Soul",
            "image":"card8",
            "strengthUp":2,
            "strengthRight":1,
            "strengthDown":6,
            "strengthLeft":1,
            "element":0
         },{
            "displayName":"Caterchipillar",
            "image":"card9",
            "strengthUp":4,
            "strengthRight":2,
            "strengthDown":4,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"Cockatrice",
            "image":"card10",
            "strengthUp":2,
            "strengthRight":1,
            "strengthDown":2,
            "strengthLeft":6,
            "element":2
         },{
            "displayName":"Grat",
            "image":"card11",
            "strengthUp":7,
            "strengthRight":1,
            "strengthDown":3,
            "strengthLeft":1,
            "element":0
         },{
            "displayName":"Buel",
            "image":"card12",
            "strengthUp":6,
            "strengthRight":2,
            "strengthDown":2,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"Mesmerize",
            "image":"card13",
            "strengthUp":5,
            "strengthRight":3,
            "strengthDown":3,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Glacial Eye",
            "image":"card14",
            "strengthUp":6,
            "strengthRight":1,
            "strengthDown":4,
            "strengthLeft":3,
            "element":4
         },{
            "displayName":"Belhelmel",
            "image":"card15",
            "strengthUp":3,
            "strengthRight":4,
            "strengthDown":5,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"Thrustaevis",
            "image":"card16",
            "strengthUp":5,
            "strengthRight":3,
            "strengthDown":2,
            "strengthLeft":5,
            "element":8
         },{
            "displayName":"Anacondaur",
            "image":"card17",
            "strengthUp":5,
            "strengthRight":1,
            "strengthDown":3,
            "strengthLeft":5,
            "element":6
         },{
            "displayName":"Creeps",
            "image":"card18",
            "strengthUp":5,
            "strengthRight":2,
            "strengthDown":5,
            "strengthLeft":2,
            "element":2
         },{
            "displayName":"Grendel",
            "image":"card19",
            "strengthUp":4,
            "strengthRight":4,
            "strengthDown":5,
            "strengthLeft":2,
            "element":2
         },{
            "displayName":"Jelleye",
            "image":"card20",
            "strengthUp":3,
            "strengthRight":2,
            "strengthDown":1,
            "strengthLeft":7,
            "element":0
         },{
            "displayName":"Grand Mantis",
            "image":"card21",
            "strengthUp":5,
            "strengthRight":2,
            "strengthDown":5,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"Forbidden",
            "image":"card22",
            "strengthUp":6,
            "strengthRight":6,
            "strengthDown":3,
            "strengthLeft":2,
            "element":0
         },{
            "displayName":"Armadodo",
            "image":"card23",
            "strengthUp":6,
            "strengthRight":3,
            "strengthDown":1,
            "strengthLeft":6,
            "element":5
         },{
            "displayName":"Tri-Face",
            "image":"card24",
            "strengthUp":3,
            "strengthRight":5,
            "strengthDown":5,
            "strengthLeft":5,
            "element":6
         },{
            "displayName":"Fastitocalon",
            "image":"card25",
            "strengthUp":7,
            "strengthRight":5,
            "strengthDown":1,
            "strengthLeft":3,
            "element":5
         },{
            "displayName":"Snow Lion",
            "image":"card26",
            "strengthUp":7,
            "strengthRight":1,
            "strengthDown":5,
            "strengthLeft":3,
            "element":4
         },{
            "displayName":"Ochu",
            "image":"card27",
            "strengthUp":5,
            "strengthRight":6,
            "strengthDown":3,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"SAM08G",
            "image":"card28",
            "strengthUp":5,
            "strengthRight":6,
            "strengthDown":2,
            "strengthLeft":4,
            "element":3
         },{
            "displayName":"Death Claw",
            "image":"card29",
            "strengthUp":4,
            "strengthRight":4,
            "strengthDown":7,
            "strengthLeft":2,
            "element":3
         },{
            "displayName":"Cactuar",
            "image":"card30",
            "strengthUp":6,
            "strengthRight":2,
            "strengthDown":6,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"Tonberry",
            "image":"card31",
            "strengthUp":3,
            "strengthRight":6,
            "strengthDown":4,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Abyss Worm",
            "image":"card32",
            "strengthUp":7,
            "strengthRight":2,
            "strengthDown":3,
            "strengthLeft":5,
            "element":5
         },{
            "displayName":"Turtapod",
            "image":"card33",
            "strengthUp":2,
            "strengthRight":3,
            "strengthDown":6,
            "strengthLeft":7,
            "element":0
         },{
            "displayName":"Vysage",
            "image":"card34",
            "strengthUp":6,
            "strengthRight":5,
            "strengthDown":4,
            "strengthLeft":5,
            "element":0
         },{
            "displayName":"T-Rexaur",
            "image":"card35",
            "strengthUp":4,
            "strengthRight":6,
            "strengthDown":2,
            "strengthLeft":7,
            "element":0
         },{
            "displayName":"Bomb",
            "image":"card36",
            "strengthUp":2,
            "strengthRight":7,
            "strengthDown":6,
            "strengthLeft":3,
            "element":3
         },{
            "displayName":"Blitz",
            "image":"card37",
            "strengthUp":1,
            "strengthRight":6,
            "strengthDown":4,
            "strengthLeft":7,
            "element":2
         },{
            "displayName":"Wendigo",
            "image":"card38",
            "strengthUp":7,
            "strengthRight":3,
            "strengthDown":1,
            "strengthLeft":6,
            "element":0
         },{
            "displayName":"Torama",
            "image":"card39",
            "strengthUp":7,
            "strengthRight":4,
            "strengthDown":4,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Imp",
            "image":"card40",
            "strengthUp":3,
            "strengthRight":7,
            "strengthDown":3,
            "strengthLeft":6,
            "element":0
         },{
            "displayName":"Blue Dragon",
            "image":"card41",
            "strengthUp":6,
            "strengthRight":2,
            "strengthDown":7,
            "strengthLeft":3,
            "element":6
         },{
            "displayName":"Adamantoise",
            "image":"card42",
            "strengthUp":4,
            "strengthRight":5,
            "strengthDown":5,
            "strengthLeft":6,
            "element":5
         },{
            "displayName":"Hexadragon",
            "image":"card43",
            "strengthUp":7,
            "strengthRight":5,
            "strengthDown":4,
            "strengthLeft":3,
            "element":3
         },{
            "displayName":"Iron Giant",
            "image":"card44",
            "strengthUp":6,
            "strengthRight":5,
            "strengthDown":6,
            "strengthLeft":5,
            "element":0
         },{
            "displayName":"Behemoth",
            "image":"card45",
            "strengthUp":3,
            "strengthRight":6,
            "strengthDown":5,
            "strengthLeft":7,
            "element":0
         },{
            "displayName":"Chimera",
            "image":"card46",
            "strengthUp":7,
            "strengthRight":6,
            "strengthDown":5,
            "strengthLeft":3,
            "element":1
         },{
            "displayName":"PuPu",
            "image":"card47",
            "strengthUp":3,
            "strengthRight":10,
            "strengthDown":2,
            "strengthLeft":1,
            "element":0
         },{
            "displayName":"Elastoid",
            "image":"card48",
            "strengthUp":6,
            "strengthRight":2,
            "strengthDown":6,
            "strengthLeft":7,
            "element":0
         },{
            "displayName":"GIM47N",
            "image":"card49",
            "strengthUp":5,
            "strengthRight":5,
            "strengthDown":7,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Malboro",
            "image":"card50",
            "strengthUp":7,
            "strengthRight":7,
            "strengthDown":4,
            "strengthLeft":2,
            "element":6
         },{
            "displayName":"Ruby Dragon",
            "image":"card51",
            "strengthUp":7,
            "strengthRight":2,
            "strengthDown":7,
            "strengthLeft":4,
            "element":3
         },{
            "displayName":"Elnoyle",
            "image":"card52",
            "strengthUp":5,
            "strengthRight":3,
            "strengthDown":7,
            "strengthLeft":6,
            "element":0
         },{
            "displayName":"Tonberry King",
            "image":"card53",
            "strengthUp":4,
            "strengthRight":6,
            "strengthDown":7,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Wedge, Biggs",
            "image":"card54",
            "strengthUp":6,
            "strengthRight":6,
            "strengthDown":2,
            "strengthLeft":7,
            "element":0
         },{
            "displayName":"Fujin Raijin",
            "image":"card55",
            "strengthUp":2,
            "strengthRight":8,
            "strengthDown":8,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Elvoret",
            "image":"card56",
            "strengthUp":7,
            "strengthRight":8,
            "strengthDown":3,
            "strengthLeft":4,
            "element":8
         },{
            "displayName":"X-ATM092",
            "image":"card57",
            "strengthUp":4,
            "strengthRight":8,
            "strengthDown":7,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"Granaldo",
            "image":"card58",
            "strengthUp":7,
            "strengthRight":2,
            "strengthDown":8,
            "strengthLeft":5,
            "element":0
         },{
            "displayName":"Gerogero",
            "image":"card59",
            "strengthUp":1,
            "strengthRight":8,
            "strengthDown":8,
            "strengthLeft":3,
            "element":6
         },{
            "displayName":"Iguion",
            "image":"card60",
            "strengthUp":8,
            "strengthRight":2,
            "strengthDown":8,
            "strengthLeft":2,
            "element":0
         },{
            "displayName":"Abadon",
            "image":"card61",
            "strengthUp":6,
            "strengthRight":8,
            "strengthDown":4,
            "strengthLeft":5,
            "element":0
         },{
            "displayName":"Trauma",
            "image":"card62",
            "strengthUp":4,
            "strengthRight":8,
            "strengthDown":5,
            "strengthLeft":6,
            "element":0
         },{
            "displayName":"Oilboyle",
            "image":"card63",
            "strengthUp":1,
            "strengthRight":8,
            "strengthDown":4,
            "strengthLeft":8,
            "element":0
         },{
            "displayName":"Shumi",
            "image":"card64",
            "strengthUp":6,
            "strengthRight":5,
            "strengthDown":8,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Krysta",
            "image":"card65",
            "strengthUp":7,
            "strengthRight":5,
            "strengthDown":8,
            "strengthLeft":1,
            "element":0
         },{
            "displayName":"Propagator",
            "image":"card66",
            "strengthUp":8,
            "strengthRight":4,
            "strengthDown":4,
            "strengthLeft":8,
            "element":0
         },{
            "displayName":"Jumbo Cactuar",
            "image":"card67",
            "strengthUp":8,
            "strengthRight":8,
            "strengthDown":4,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Tri-Point",
            "image":"card68",
            "strengthUp":8,
            "strengthRight":5,
            "strengthDown":2,
            "strengthLeft":8,
            "element":2
         },{
            "displayName":"Gargantua",
            "image":"card69",
            "strengthUp":5,
            "strengthRight":6,
            "strengthDown":6,
            "strengthLeft":8,
            "element":0
         },{
            "displayName":"Mobile Type 8",
            "image":"card70",
            "strengthUp":8,
            "strengthRight":6,
            "strengthDown":7,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"Sphinxara",
            "image":"card71",
            "strengthUp":8,
            "strengthRight":3,
            "strengthDown":5,
            "strengthLeft":8,
            "element":0
         },{
            "displayName":"Tiamat",
            "image":"card72",
            "strengthUp":8,
            "strengthRight":8,
            "strengthDown":5,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"BGH251F2",
            "image":"card73",
            "strengthUp":5,
            "strengthRight":7,
            "strengthDown":8,
            "strengthLeft":5,
            "element":0
         },{
            "displayName":"Red Giant",
            "image":"card74",
            "strengthUp":6,
            "strengthRight":8,
            "strengthDown":4,
            "strengthLeft":7,
            "element":0
         },{
            "displayName":"Catoblepas",
            "image":"card75",
            "strengthUp":1,
            "strengthRight":8,
            "strengthDown":7,
            "strengthLeft":7,
            "element":0
         },{
            "displayName":"Ultima Weapon",
            "image":"card76",
            "strengthUp":7,
            "strengthRight":7,
            "strengthDown":2,
            "strengthLeft":8,
            "element":0
         },{
            "displayName":"Chubby Chocobo",
            "image":"card77",
            "strengthUp":4,
            "strengthRight":4,
            "strengthDown":8,
            "strengthLeft":9,
            "element":0
         },{
            "displayName":"Angelo",
            "image":"card78",
            "strengthUp":9,
            "strengthRight":6,
            "strengthDown":7,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"Gilgamesh",
            "image":"card79",
            "strengthUp":3,
            "strengthRight":7,
            "strengthDown":9,
            "strengthLeft":6,
            "element":0
         },{
            "displayName":"MiniMog",
            "image":"card80",
            "strengthUp":9,
            "strengthRight":3,
            "strengthDown":9,
            "strengthLeft":2,
            "element":0
         },{
            "displayName":"Chicobo",
            "image":"card81",
            "strengthUp":9,
            "strengthRight":4,
            "strengthDown":8,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Quezacotl",
            "image":"card82",
            "strengthUp":2,
            "strengthRight":9,
            "strengthDown":9,
            "strengthLeft":4,
            "element":2
         },{
            "displayName":"Shiva",
            "image":"card83",
            "strengthUp":6,
            "strengthRight":7,
            "strengthDown":4,
            "strengthLeft":9,
            "element":4
         },{
            "displayName":"Ifrit",
            "image":"card84",
            "strengthUp":9,
            "strengthRight":6,
            "strengthDown":2,
            "strengthLeft":8,
            "element":3
         },{
            "displayName":"Siren",
            "image":"card85",
            "strengthUp":8,
            "strengthRight":9,
            "strengthDown":6,
            "strengthLeft":2,
            "element":0
         },{
            "displayName":"Sacred",
            "image":"card86",
            "strengthUp":5,
            "strengthRight":1,
            "strengthDown":9,
            "strengthLeft":9,
            "element":5
         },{
            "displayName":"Minotaur",
            "image":"card87",
            "strengthUp":9,
            "strengthRight":5,
            "strengthDown":2,
            "strengthLeft":9,
            "element":5
         },{
            "displayName":"Carbuncle",
            "image":"card88",
            "strengthUp":8,
            "strengthRight":4,
            "strengthDown":10,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Diablos",
            "image":"card89",
            "strengthUp":5,
            "strengthRight":10,
            "strengthDown":8,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"Leviathan",
            "image":"card90",
            "strengthUp":7,
            "strengthRight":10,
            "strengthDown":1,
            "strengthLeft":7,
            "element":1
         },{
            "displayName":"Odin",
            "image":"card91",
            "strengthUp":8,
            "strengthRight":10,
            "strengthDown":3,
            "strengthLeft":5,
            "element":0
         },{
            "displayName":"Pandemona",
            "image":"card92",
            "strengthUp":10,
            "strengthRight":1,
            "strengthDown":7,
            "strengthLeft":7,
            "element":8
         },{
            "displayName":"Cerberus",
            "image":"card93",
            "strengthUp":7,
            "strengthRight":4,
            "strengthDown":6,
            "strengthLeft":10,
            "element":0
         },{
            "displayName":"Alexander",
            "image":"card94",
            "strengthUp":9,
            "strengthRight":10,
            "strengthDown":4,
            "strengthLeft":2,
            "element":7
         },{
            "displayName":"Phoenix",
            "image":"card95",
            "strengthUp":7,
            "strengthRight":2,
            "strengthDown":7,
            "strengthLeft":10,
            "element":3
         },{
            "displayName":"Bahamut",
            "image":"card96",
            "strengthUp":10,
            "strengthRight":8,
            "strengthDown":2,
            "strengthLeft":6,
            "element":0
         },{
            "displayName":"Doomtrain",
            "image":"card97",
            "strengthUp":3,
            "strengthRight":1,
            "strengthDown":10,
            "strengthLeft":10,
            "element":6
         },{
            "displayName":"Eden",
            "image":"card98",
            "strengthUp":4,
            "strengthRight":4,
            "strengthDown":9,
            "strengthLeft":10,
            "element":0
         },{
            "displayName":"Ward",
            "image":"card99",
            "strengthUp":10,
            "strengthRight":7,
            "strengthDown":2,
            "strengthLeft":8,
            "element":0
         },{
            "displayName":"Kiros",
            "image":"card100",
            "strengthUp":6,
            "strengthRight":7,
            "strengthDown":6,
            "strengthLeft":10,
            "element":0
         },{
            "displayName":"Laguna",
            "image":"card101",
            "strengthUp":5,
            "strengthRight":10,
            "strengthDown":3,
            "strengthLeft":9,
            "element":0
         },{
            "displayName":"Selphie",
            "image":"card102",
            "strengthUp":10,
            "strengthRight":8,
            "strengthDown":6,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Quistis",
            "image":"card103",
            "strengthUp":9,
            "strengthRight":6,
            "strengthDown":10,
            "strengthLeft":2,
            "element":0
         },{
            "displayName":"Irvine",
            "image":"card104",
            "strengthUp":2,
            "strengthRight":6,
            "strengthDown":9,
            "strengthLeft":10,
            "element":0
         },{
            "displayName":"Zell",
            "image":"card105",
            "strengthUp":8,
            "strengthRight":5,
            "strengthDown":10,
            "strengthLeft":6,
            "element":0
         },{
            "displayName":"Rinoa",
            "image":"card106",
            "strengthUp":4,
            "strengthRight":10,
            "strengthDown":2,
            "strengthLeft":10,
            "element":0
         },{
            "displayName":"Edea",
            "image":"card107",
            "strengthUp":10,
            "strengthRight":10,
            "strengthDown":3,
            "strengthLeft":3,
            "element":0
         },{
            "displayName":"Seifer",
            "image":"card108",
            "strengthUp":6,
            "strengthRight":9,
            "strengthDown":10,
            "strengthLeft":4,
            "element":0
         },{
            "displayName":"Squall",
            "image":"card109",
            "strengthUp":10,
            "strengthRight":4,
            "strengthDown":6,
            "strengthLeft":9,
            "element":0
         }];